# Generated by Django 5.1.2 on 2024-10-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_system', '0002_diseasedetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='No bio provided.', null=True),
        ),
    ]
